server:
 port: 443
 servlet: 
 

  ssl:
    enabled: true
    key-alias: local_ssl
    key-store-key: classpath:local-ssl.p12
    key-store-type: PKCS12 
    key-password: 123456789
    key-store-password: 123456789 
 